# Generated by Django 3.1 on 2020-09-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='author_id',
            new_name='author',
        ),
    ]
