# Generated by Django 3.1 on 2020-10-17 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reci', '0004_auto_20201017_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='whishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recepe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.recipes')),
            ],
        ),
    ]
