# Generated by Django 3.1 on 2020-10-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
