# Generated by Django 3.1 on 2020-10-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0010_recipes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='title',
            field=models.CharField(max_length=200, verbose_name='User Recipes'),
        ),
    ]
