# Generated by Django 3.1 on 2020-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0011_auto_20201028_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='descr',
            field=models.TextField(default='SOME STRING', verbose_name='Recipes Description'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='reciepe_category',
        ),
    ]
