# Generated by Django 3.1 on 2020-10-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0013_auto_20201028_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='integredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reci.recipes')),
            ],
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
