# Generated by Django 3.1 on 2020-11-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0016_auto_20201128_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='fivestarcount',
            field=models.IntegerField(default=0),
        ),
    ]
