# Generated by Django 3.1 on 2020-12-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reci', '0017_recipes_fivestarcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
